import type { Metadata } from "next";
import { Anton, Anton_SC, Roboto_Mono } from "next/font/google";
import "@/css/global.css";
import "@/css/_typography.css";
import "@/css/_utils.css";

const anton = Anton({
  subsets: ["latin-ext"],
  weight: ['400'],
  variable: '--font-big'
})

const antonSc = Anton_SC({
  subsets: ["latin-ext"],
  weight: ['400'],
  variable: '--font-big-uppercase'
})

const robotoMono = Roboto_Mono({
  subsets: ["latin-ext"],
  weight: ['400', '500', '700'],
  variable: '--font-slab'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body
        className={`${anton.variable} ${antonSc.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

